--<ScriptOptions statementTerminator=";"/>

CREATE TABLE CREATOR (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		NAME VARCHAR(256),
		CONTROLLED_VOCABULARY_ID INTEGER,
		CONTACT_URL VARCHAR(512),
		CONTACT_EMAIL VARCHAR(256),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE CONTROLLED_VOCABULARY (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		VOCAB VARCHAR(32),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE DATABASECHANGELOGLOCK (
		ID INTEGER NOT NULL,
		LOCKED null NOT NULL,
		LOCKGRANTED TIMESTAMP,
		LOCKEDBY VARCHAR(255)
	);

CREATE TABLE DATABASECHANGELOG (
		ID VARCHAR(63) NOT NULL,
		AUTHOR VARCHAR(63) NOT NULL,
		FILENAME VARCHAR(200) NOT NULL,
		DATEEXECUTED TIMESTAMP NOT NULL,
		ORDEREXECUTED INTEGER NOT NULL,
		EXECTYPE VARCHAR(10) NOT NULL,
		MD5SUM VARCHAR(35),
		DESCRIPTION VARCHAR(255),
		COMMENTS VARCHAR(255),
		TAG VARCHAR(255),
		LIQUIBASE VARCHAR(20)
	);

CREATE TABLE PUBLISHER_JOIN (
		DATASET_ID INTEGER,
		PUBLISHER_ID INTEGER,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE KEYWORD_JOIN (
		DATASET_ID INTEGER,
		KEYWORD_ID INTEGER,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE PROJECT_JOIN (
		DATASET_ID INTEGER,
		PROJECT_ID INTEGER,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE DATE_JOIN (
		DATASET_ID INTEGER,
		DATE_TYPE_FORMATTED_ID INTEGER,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE TASK (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		NAME VARCHAR(64),
		PARAMS VARCHAR(256)
	);

CREATE TABLE CATALOG (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 2),
		LOCATION VARCHAR(512),
		NAME VARCHAR(64),
		EXPIRES DATE,
		VERSION VARCHAR(8),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE KEYWORD (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		VALUE VARCHAR(64),
		CONTROLLED_VOCABULARY_ID INTEGER,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE SPATIAL_RANGE_TYPE (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(32)
	);

CREATE TABLE EXCLUDE_TYPE (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(8)
	);

CREATE TABLE SPATIAL_RANGE (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		GEOSPATIAL_COVERAGE_ID INTEGER,
		SPATIAL_RANGE_TYPE_ID INTEGER,
		START DOUBLE,
		SIZE DOUBLE,
		RESOLUTION DOUBLE,
		UNITS VARCHAR(32),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE DATASET (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		CATALOG_ID INTEGER,
		COLLECTION_TYPE_ID INTEGER,
		DATA_TYPE_ID INTEGER,
		NAME VARCHAR(64),
		NCID VARCHAR(128),
		AUTHORITY VARCHAR(64),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE PROJECT (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		NAME VARCHAR(256),
		CONTROLLED_VOCABULARY_ID INTEGER,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE DATE_TYPE_FORMATTED (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		FORMAT VARCHAR(256),
		VALUE VARCHAR(256),
		DATE_TYPE_ENUM_ID INTEGER,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE DATA_FORMAT (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(32)
	);

CREATE TABLE TIME_COVERAGE (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		DATASET_ID INTEGER,
		START_ID INTEGER,
		END_ID INTEGER,
		DURATION VARCHAR(32),
		RESOLUTION VARCHAR(32),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE COLLECTION_TYPE (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(32)
	);

CREATE TABLE RENAME_MAPPING (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 38),
		ARCHIVE_ID INTEGER,
		FROM_NAME VARCHAR(256),
		TO_NAME VARCHAR(256),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE UP_DOWN_TYPE (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(4)
	);

CREATE TABLE SERVICE_TYPE (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(32)
	);

CREATE TABLE CONTRIBUTOR (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		ROLE VARCHAR(64),
		TEXT VARCHAR(256),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE DATA_TYPE (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(32)
	);

CREATE TABLE ARCHIVE_CONFIG (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 15),
		INPUT_DIR VARCHAR(256),
		OUTPUT_DIR VARCHAR(256),
		COMPLETE_DIR VARCHAR(256),
		FILE_REGEX VARCHAR(256),
		RFC_CODE INTEGER,
		UNLIMITED_DIM VARCHAR(256),
		UNLIMITED_UNITS VARCHAR(256),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false,
		NAME CHAR(4) NOT NULL,
		NOTES VARCHAR(255)
	);

CREATE TABLE INGEST (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		CATALOG_ID INTEGER,
		NAME VARCHAR(128),
		FTPLOCATION VARCHAR(512),
		RESCANEVERY BIGINT,
		FILEREGEX VARCHAR(64),
		SUCCESSDATE DATE,
		SUCCESSTIME TIME,
		USERNAME VARCHAR(64),
		PASSWORD VARCHAR(64),
		ACTIVE null,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE ETL_HISTORY (
		ID INTEGER DEFAULT GENERATED_BY_DEFAULT NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 10),
		ARCHIVE_ID INTEGER,
		TS TIMESTAMP,
		OUTCOME VARCHAR(255)
	);

CREATE TABLE GEOSPATIAL_COVERAGE (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		DATASET_ID INTEGER,
		CONTROLLED_VOCABULARY_ID INTEGER,
		NAME VARCHAR(128),
		ZPOSITIVE_ID INTEGER,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE ACCESS (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		DATASET_ID INTEGER,
		SERVICE_ID INTEGER,
		DATAFORMAT_ID INTEGER,
		URL_PATH VARCHAR(512),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE DATE_TYPE_ENUM (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(32)
	);

CREATE TABLE GLOBAL_CONFIG (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		BASE_DIR VARCHAR(512),
		THREDDS_DIR VARCHAR(512),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE CREATOR_JOIN (
		DATASET_ID INTEGER,
		CREATOR_ID INTEGER,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE EXCLUDE_MAPPING (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 146),
		ARCHIVE_ID INTEGER,
		EXCLUDE_TYPE_ID INTEGER,
		EXCLUDE_TEXT VARCHAR(256),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE SERVICE (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		CATALOG_ID INTEGER,
		SERVICE_ID INTEGER,
		SERVICE_TYPE_ID INTEGER,
		NAME VARCHAR(64),
		BASE VARCHAR(32),
		DESCRIPTION VARCHAR(512),
		SUFFIX VARCHAR(32),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE DOCUMENTATION_TYPE (
		ID INTEGER NOT NULL,
		TYPE VARCHAR(32)
	);

CREATE TABLE CONTRIBUTOR_JOIN (
		DATASET_ID INTEGER,
		CONTRIBUTOR_ID INTEGER,
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE DOCUMENTATION (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		DATASET_ID INTEGER,
		DOCUMENTATION_TYPE_ID INTEGER,
		XLINK_HREF VARCHAR(256),
		XLINK_TITLE VARCHAR(256),
		TEXT VARCHAR(1024),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE PUBLISHER (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		NAME VARCHAR(256),
		CONTROLLED_VOCABULARY_ID INTEGER,
		CONTACT_URL VARCHAR(512),
		CONTACT_EMAIL VARCHAR(256),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE TABLE PROPERTY (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		DATASET_ID INTEGER,
		NAME VARCHAR(128),
		VALUE VARCHAR(512),
		INSERTED null DEFAULT false,
		UPDATED null DEFAULT false
	);

CREATE UNIQUE INDEX SQL130311202651270 ON ARCHIVE_CONFIG (ID ASC);

CREATE INDEX SQL130311202652211 ON PROJECT (CONTROLLED_VOCABULARY_ID ASC);

CREATE INDEX SQL130311202653030 ON DATE_JOIN (DATASET_ID ASC);

CREATE INDEX SQL130311202653031 ON DATE_JOIN (DATE_TYPE_FORMATTED_ID ASC);

CREATE INDEX SQL130311202651771 ON SERVICE (SERVICE_TYPE_ID ASC);

CREATE INDEX SQL130311202651651 ON DATASET (CATALOG_ID ASC);

CREATE UNIQUE INDEX SQL130530090109640 ON DATABASECHANGELOGLOCK (ID ASC);

CREATE UNIQUE INDEX SQL130311202650920 ON COLLECTION_TYPE (ID ASC);

CREATE INDEX SQL130311202651471 ON RENAME_MAPPING (ARCHIVE_ID ASC);

CREATE INDEX SQL130311202652800 ON CONTRIBUTOR_JOIN (DATASET_ID ASC);

CREATE UNIQUE INDEX SQL130311202652150 ON CREATOR (ID ASC);

CREATE UNIQUE INDEX SQL130530090109910 ON DATABASECHANGELOG (ID ASC, AUTHOR ASC, FILENAME ASC);

CREATE INDEX SQL130311202652582 ON TIME_COVERAGE (START_ID ASC);

CREATE INDEX SQL130311202652861 ON CREATOR_JOIN (CREATOR_ID ASC);

CREATE INDEX SQL130311202652292 ON GEOSPATIAL_COVERAGE (CONTROLLED_VOCABULARY_ID ASC);

CREATE UNIQUE INDEX SQL130311202651200 ON UP_DOWN_TYPE (ID ASC);

CREATE UNIQUE INDEX SQL130311202651770 ON SERVICE (ID ASC);

CREATE INDEX SQL130311202652801 ON CONTRIBUTOR_JOIN (CONTRIBUTOR_ID ASC);

CREATE UNIQUE INDEX SQL130311202651650 ON DATASET (ID ASC);

CREATE INDEX SQL130311202652081 ON KEYWORD (CONTROLLED_VOCABULARY_ID ASC);

CREATE UNIQUE INDEX SQL130311202651250 ON GLOBAL_CONFIG (ID ASC);

CREATE INDEX SQL130311202652291 ON GEOSPATIAL_COVERAGE (DATASET_ID ASC);

CREATE INDEX SQL130311202652293 ON GEOSPATIAL_COVERAGE (ZPOSITIVE_ID ASC);

CREATE INDEX SQL130311202651972 ON DOCUMENTATION (DOCUMENTATION_TYPE_ID ASC);

CREATE INDEX SQL130311202652583 ON TIME_COVERAGE (END_ID ASC);

CREATE UNIQUE INDEX SQL130311202652240 ON PUBLISHER (ID ASC);

CREATE UNIQUE INDEX SQL130311202651810 ON ACCESS (ID ASC);

CREATE INDEX SQL130311202652461 ON SPATIAL_RANGE (GEOSPATIAL_COVERAGE_ID ASC);

CREATE INDEX SQL130311202652462 ON SPATIAL_RANGE (SPATIAL_RANGE_TYPE_ID ASC);

CREATE UNIQUE INDEX SQL130311202652040 ON PROPERTY (ID ASC);

CREATE INDEX SQL130311202652980 ON PUBLISHER_JOIN (DATASET_ID ASC);

CREATE UNIQUE INDEX SQL130311202652180 ON DATE_TYPE_FORMATTED (ID ASC);

CREATE INDEX SQL130311202651652 ON DATASET (COLLECTION_TYPE_ID ASC);

CREATE INDEX SQL130311202651340 ON EXCLUDE_MAPPING (EXCLUDE_TYPE_ID ASC);

CREATE UNIQUE INDEX SQL130311202651320 ON EXCLUDE_MAPPING (ID ASC);

CREATE INDEX SQL130311202652941 ON PROJECT_JOIN (PROJECT_ID ASC);

CREATE UNIQUE INDEX SQL130311202651570 ON INGEST (ID ASC);

CREATE UNIQUE INDEX SQL130311202651130 ON DOCUMENTATION_TYPE (ID ASC);

CREATE UNIQUE INDEX SQL130311202652290 ON GEOSPATIAL_COVERAGE (ID ASC);

CREATE INDEX SQL130530095627830 ON ETL_HISTORY (ARCHIVE_ID ASC);

CREATE INDEX SQL130311202652181 ON DATE_TYPE_FORMATTED (DATE_TYPE_ENUM_ID ASC);

CREATE INDEX SQL130311202652860 ON CREATOR_JOIN (DATASET_ID ASC);

CREATE UNIQUE INDEX SQL130311202651170 ON DATE_TYPE_ENUM (ID ASC);

CREATE INDEX SQL130311202652981 ON PUBLISHER_JOIN (PUBLISHER_ID ASC);

CREATE INDEX SQL130311202652940 ON PROJECT_JOIN (DATASET_ID ASC);

CREATE INDEX SQL130311202651811 ON ACCESS (DATASET_ID ASC);

CREATE UNIQUE INDEX SQL130311202651970 ON DOCUMENTATION (ID ASC);

CREATE UNIQUE INDEX SQL130311202651070 ON DATA_TYPE (ID ASC);

CREATE UNIQUE INDEX SQL130311202651290 ON EXCLUDE_TYPE (ID ASC);

CREATE UNIQUE INDEX SQL130311202651180 ON SPATIAL_RANGE_TYPE (ID ASC);

CREATE UNIQUE INDEX SQL130311202651150 ON SERVICE_TYPE (ID ASC);

CREATE INDEX SQL130311202651571 ON INGEST (CATALOG_ID ASC);

CREATE UNIQUE INDEX SQL130311202652460 ON SPATIAL_RANGE (ID ASC);

CREATE UNIQUE INDEX SQL130311202651470 ON RENAME_MAPPING (ID ASC);

CREATE INDEX SQL130311202651812 ON ACCESS (SERVICE_ID ASC);

CREATE UNIQUE INDEX SQL130311202651540 ON CATALOG (ID ASC);

CREATE UNIQUE INDEX SQL130311202651230 ON CONTROLLED_VOCABULARY (ID ASC);

CREATE INDEX SQL130311202651653 ON DATASET (DATA_TYPE_ID ASC);

CREATE INDEX SQL130311202652041 ON PROPERTY (DATASET_ID ASC);

CREATE UNIQUE INDEX SQL130311202652130 ON CONTRIBUTOR (ID ASC);

CREATE INDEX SQL130311202652581 ON TIME_COVERAGE (DATASET_ID ASC);

CREATE INDEX SQL130311202651813 ON ACCESS (DATAFORMAT_ID ASC);

CREATE UNIQUE INDEX SQL130530095627790 ON ETL_HISTORY (ID ASC);

CREATE INDEX SQL130311202651330 ON EXCLUDE_MAPPING (ARCHIVE_ID ASC);

CREATE UNIQUE INDEX SQL130311202652080 ON KEYWORD (ID ASC);

CREATE INDEX SQL130311202652151 ON CREATOR (CONTROLLED_VOCABULARY_ID ASC);

CREATE INDEX SQL130311202652241 ON PUBLISHER (CONTROLLED_VOCABULARY_ID ASC);

CREATE UNIQUE INDEX SQL130311202651110 ON DATA_FORMAT (ID ASC);

CREATE INDEX SQL130311202652700 ON KEYWORD_JOIN (DATASET_ID ASC);

CREATE UNIQUE INDEX SQL130311202652580 ON TIME_COVERAGE (ID ASC);

CREATE INDEX SQL130311202652701 ON KEYWORD_JOIN (KEYWORD_ID ASC);

CREATE UNIQUE INDEX SQL130311202652210 ON PROJECT (ID ASC);

CREATE INDEX SQL130311202651971 ON DOCUMENTATION (DATASET_ID ASC);

ALTER TABLE TIME_COVERAGE ADD CONSTRAINT SQL130311202652580 PRIMARY KEY (ID);

ALTER TABLE SERVICE_TYPE ADD CONSTRAINT SQL130311202651150 PRIMARY KEY (ID);

ALTER TABLE EXCLUDE_MAPPING ADD CONSTRAINT SQL130311202651320 PRIMARY KEY (ID);

ALTER TABLE RENAME_MAPPING ADD CONSTRAINT SQL130311202651470 PRIMARY KEY (ID);

ALTER TABLE CATALOG ADD CONSTRAINT SQL130311202651540 PRIMARY KEY (ID);

ALTER TABLE SERVICE ADD CONSTRAINT SQL130311202651770 PRIMARY KEY (ID);

ALTER TABLE ARCHIVE_CONFIG ADD CONSTRAINT SQL130311202651270 PRIMARY KEY (ID);

ALTER TABLE SPATIAL_RANGE ADD CONSTRAINT SQL130311202652460 PRIMARY KEY (ID);

ALTER TABLE DATABASECHANGELOGLOCK ADD CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID);

ALTER TABLE PROPERTY ADD CONSTRAINT SQL130311202652040 PRIMARY KEY (ID);

ALTER TABLE DATA_TYPE ADD CONSTRAINT SQL130311202651070 PRIMARY KEY (ID);

ALTER TABLE GLOBAL_CONFIG ADD CONSTRAINT SQL130311202651250 PRIMARY KEY (ID);

ALTER TABLE UP_DOWN_TYPE ADD CONSTRAINT SQL130311202651200 PRIMARY KEY (ID);

ALTER TABLE SPATIAL_RANGE_TYPE ADD CONSTRAINT SQL130311202651180 PRIMARY KEY (ID);

ALTER TABLE EXCLUDE_TYPE ADD CONSTRAINT SQL130311202651290 PRIMARY KEY (ID);

ALTER TABLE PUBLISHER ADD CONSTRAINT SQL130311202652240 PRIMARY KEY (ID);

ALTER TABLE GEOSPATIAL_COVERAGE ADD CONSTRAINT SQL130311202652290 PRIMARY KEY (ID);

ALTER TABLE DATE_TYPE_ENUM ADD CONSTRAINT SQL130311202651170 PRIMARY KEY (ID);

ALTER TABLE ACCESS ADD CONSTRAINT SQL130311202651810 PRIMARY KEY (ID);

ALTER TABLE CREATOR ADD CONSTRAINT SQL130311202652150 PRIMARY KEY (ID);

ALTER TABLE ETL_HISTORY ADD CONSTRAINT PK_ETL_HISTORY PRIMARY KEY (ID);

ALTER TABLE DOCUMENTATION ADD CONSTRAINT SQL130311202651970 PRIMARY KEY (ID);

ALTER TABLE DATABASECHANGELOG ADD CONSTRAINT PK_DATABASECHANGELOG PRIMARY KEY (ID, AUTHOR, FILENAME);

ALTER TABLE CONTRIBUTOR ADD CONSTRAINT SQL130311202652130 PRIMARY KEY (ID);

ALTER TABLE CONTROLLED_VOCABULARY ADD CONSTRAINT SQL130311202651230 PRIMARY KEY (ID);

ALTER TABLE KEYWORD ADD CONSTRAINT SQL130311202652080 PRIMARY KEY (ID);

ALTER TABLE DATE_TYPE_FORMATTED ADD CONSTRAINT SQL130311202652180 PRIMARY KEY (ID);

ALTER TABLE DATASET ADD CONSTRAINT SQL130311202651650 PRIMARY KEY (ID);

ALTER TABLE INGEST ADD CONSTRAINT SQL130311202651570 PRIMARY KEY (ID);

ALTER TABLE DATA_FORMAT ADD CONSTRAINT SQL130311202651110 PRIMARY KEY (ID);

ALTER TABLE DOCUMENTATION_TYPE ADD CONSTRAINT SQL130311202651130 PRIMARY KEY (ID);

ALTER TABLE COLLECTION_TYPE ADD CONSTRAINT SQL130311202650920 PRIMARY KEY (ID);

ALTER TABLE PROJECT ADD CONSTRAINT SQL130311202652210 PRIMARY KEY (ID);

ALTER TABLE CREATOR ADD CONSTRAINT VOCAB2_FK FOREIGN KEY (CONTROLLED_VOCABULARY_ID)
	REFERENCES CONTROLLED_VOCABULARY (ID);

ALTER TABLE ACCESS ADD CONSTRAINT SERVICE2_FK FOREIGN KEY (SERVICE_ID)
	REFERENCES SERVICE (ID)
	ON DELETE CASCADE;

ALTER TABLE ACCESS ADD CONSTRAINT DATASET1_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID)
	ON DELETE CASCADE;

ALTER TABLE TIME_COVERAGE ADD CONSTRAINT DTF2_FK FOREIGN KEY (START_ID)
	REFERENCES DATE_TYPE_FORMATTED (ID);

ALTER TABLE PROPERTY ADD CONSTRAINT DATASET3_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID)
	ON DELETE CASCADE;

ALTER TABLE DATE_JOIN ADD CONSTRAINT DTF1_FK FOREIGN KEY (DATE_TYPE_FORMATTED_ID)
	REFERENCES DATE_TYPE_FORMATTED (ID);

ALTER TABLE CREATOR_JOIN ADD CONSTRAINT DATASET7_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID);

ALTER TABLE DATE_JOIN ADD CONSTRAINT DATASET12_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID);

ALTER TABLE KEYWORD ADD CONSTRAINT VOCAB1_FK FOREIGN KEY (CONTROLLED_VOCABULARY_ID)
	REFERENCES CONTROLLED_VOCABULARY (ID);

ALTER TABLE SPATIAL_RANGE ADD CONSTRAINT SRTYPE1_FK FOREIGN KEY (SPATIAL_RANGE_TYPE_ID)
	REFERENCES SPATIAL_RANGE_TYPE (ID);

ALTER TABLE DOCUMENTATION ADD CONSTRAINT DOCTYPE_FK FOREIGN KEY (DOCUMENTATION_TYPE_ID)
	REFERENCES DOCUMENTATION_TYPE (ID);

ALTER TABLE SPATIAL_RANGE ADD CONSTRAINT GSCOVER1_FK FOREIGN KEY (GEOSPATIAL_COVERAGE_ID)
	REFERENCES GEOSPATIAL_COVERAGE (ID)
	ON DELETE CASCADE;

ALTER TABLE CONTRIBUTOR_JOIN ADD CONSTRAINT CONTRIB_FK FOREIGN KEY (CONTRIBUTOR_ID)
	REFERENCES CONTRIBUTOR (ID);

ALTER TABLE PUBLISHER ADD CONSTRAINT VOCAB4_FK FOREIGN KEY (CONTROLLED_VOCABULARY_ID)
	REFERENCES CONTROLLED_VOCABULARY (ID);

ALTER TABLE GEOSPATIAL_COVERAGE ADD CONSTRAINT VOCAB5_FK FOREIGN KEY (CONTROLLED_VOCABULARY_ID)
	REFERENCES CONTROLLED_VOCABULARY (ID);

ALTER TABLE CONTRIBUTOR_JOIN ADD CONSTRAINT DATASET6_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID);

ALTER TABLE PUBLISHER_JOIN ADD CONSTRAINT DATASET9_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID);

ALTER TABLE RENAME_MAPPING ADD CONSTRAINT ARCHIVE5_FK FOREIGN KEY (ARCHIVE_ID)
	REFERENCES ARCHIVE_CONFIG (ID)
	ON DELETE CASCADE;

ALTER TABLE TIME_COVERAGE ADD CONSTRAINT DTF3_FK FOREIGN KEY (END_ID)
	REFERENCES DATE_TYPE_FORMATTED (ID);

ALTER TABLE DATASET ADD CONSTRAINT COLLECTION1_FK FOREIGN KEY (COLLECTION_TYPE_ID)
	REFERENCES COLLECTION_TYPE (ID);

ALTER TABLE ETL_HISTORY ADD CONSTRAINT FKETLHISTORY FOREIGN KEY (ARCHIVE_ID)
	REFERENCES ARCHIVE_CONFIG (ID);

ALTER TABLE EXCLUDE_MAPPING ADD CONSTRAINT ARCHIVE2_FK FOREIGN KEY (ARCHIVE_ID)
	REFERENCES ARCHIVE_CONFIG (ID)
	ON DELETE CASCADE;

ALTER TABLE PROJECT ADD CONSTRAINT VOCAB3_FK FOREIGN KEY (CONTROLLED_VOCABULARY_ID)
	REFERENCES CONTROLLED_VOCABULARY (ID);

ALTER TABLE PROJECT_JOIN ADD CONSTRAINT DATASET8_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID);

ALTER TABLE DOCUMENTATION ADD CONSTRAINT DATASET2_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID)
	ON DELETE CASCADE;

ALTER TABLE PROJECT_JOIN ADD CONSTRAINT PROJECT_FK FOREIGN KEY (PROJECT_ID)
	REFERENCES PROJECT (ID);

ALTER TABLE CREATOR_JOIN ADD CONSTRAINT CREATOR_FK FOREIGN KEY (CREATOR_ID)
	REFERENCES CREATOR (ID);

ALTER TABLE KEYWORD_JOIN ADD CONSTRAINT DATASET5_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID);

ALTER TABLE PUBLISHER_JOIN ADD CONSTRAINT PUBLISHER_FK FOREIGN KEY (PUBLISHER_ID)
	REFERENCES PUBLISHER (ID);

ALTER TABLE TIME_COVERAGE ADD CONSTRAINT DATASET11_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID)
	ON DELETE CASCADE;

ALTER TABLE DATE_TYPE_FORMATTED ADD CONSTRAINT DATEENUM1_FK FOREIGN KEY (DATE_TYPE_ENUM_ID)
	REFERENCES DATE_TYPE_ENUM (ID);

ALTER TABLE GEOSPATIAL_COVERAGE ADD CONSTRAINT UPDOWN_FK FOREIGN KEY (ZPOSITIVE_ID)
	REFERENCES UP_DOWN_TYPE (ID);

ALTER TABLE DATASET ADD CONSTRAINT CATALOG3_FK FOREIGN KEY (CATALOG_ID)
	REFERENCES CATALOG (ID)
	ON DELETE CASCADE;

ALTER TABLE INGEST ADD CONSTRAINT CATALOG2_FK FOREIGN KEY (CATALOG_ID)
	REFERENCES CATALOG (ID)
	ON DELETE CASCADE;

ALTER TABLE DATASET ADD CONSTRAINT DATATYPE_FK FOREIGN KEY (DATA_TYPE_ID)
	REFERENCES DATA_TYPE (ID);

ALTER TABLE GEOSPATIAL_COVERAGE ADD CONSTRAINT DATASET10_FK FOREIGN KEY (DATASET_ID)
	REFERENCES DATASET (ID)
	ON DELETE CASCADE;

ALTER TABLE SERVICE ADD CONSTRAINT SERVICETYPE_FK FOREIGN KEY (SERVICE_TYPE_ID)
	REFERENCES SERVICE_TYPE (ID);

ALTER TABLE KEYWORD_JOIN ADD CONSTRAINT KEYWORD_FK FOREIGN KEY (KEYWORD_ID)
	REFERENCES KEYWORD (ID);

ALTER TABLE ACCESS ADD CONSTRAINT DATAFORMAT_FK FOREIGN KEY (DATAFORMAT_ID)
	REFERENCES DATA_FORMAT (ID);

ALTER TABLE EXCLUDE_MAPPING ADD CONSTRAINT EXCLUDE_TYPE_FK FOREIGN KEY (EXCLUDE_TYPE_ID)
	REFERENCES EXCLUDE_TYPE (ID)
	ON DELETE CASCADE;

CREATE TRIGGER CATALOG_DELETE AFTER DELETE ON CATALOG
REFERENCING OLD AS DELETED_ROW
FOR EACH ROW MODE DB2SQL
DELETE FROM service WHERE catalog_id = deleted_row.id;

CREATE TRIGGER TG_SET_TIME AFTER INSERT ON ETL_HISTORY
FOR EACH STATEMENT MODE DB2SQL
UPDATE ETL_HISTORY 
  			SET TS = CURRENT_TIMESTAMP
  			WHERE TS IS NULL;

CREATE TRIGGER SERVICE_DELETE AFTER DELETE ON SERVICE
REFERENCING OLD AS DELETED_ROW
FOR EACH ROW MODE DB2SQL
DELETE FROM service WHERE service_id = deleted_row.id;

